import Link from 'next/link';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronRight, Clock3, Dumbbell, Footprints, MoveUpRight, Play, Target, Volleyball, Zap } from 'lucide-react';
import { AppShell } from './app-shell';
import { days } from '@/lib/training';
type Props = { preview?: boolean; email?: string; completed?: number; sessions?: number; matchDays?: string[]; goal?: string; planName?: string; weekNumber?: number };
export function Dashboard({ preview = false, email, completed = 0, sessions = 0, matchDays = [], goal, planName, weekNumber = 1 }: Props) {
  const today = new Date();
  const todayIndex = (today.getDay() + 6) % 7;
  const dayIndex = preview ? 2 : todayIndex;
  const first = new Date(today); first.setDate(today.getDate() - todayIndex);
  const scheduledMatches = preview ? ['Saturday'] : matchDays;
  const metrics = preview ? { sessions: 3, completed: 18 } : { sessions, completed };
  return <AppShell preview={preview} email={email}>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-[29px] font-semibold tracking-[-1px] sm:text-[34px]">Dashboard</h1></div><div className="flex items-center gap-2 rounded-lg border border-line bg-white px-3.5 py-2.5 text-[11px] text-muted"><CalendarDays size={14}/>{today.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</div></div>
    {preview && <div className="mb-5 flex flex-wrap items-center justify-between gap-2 rounded-lg border border-line bg-canvas px-4 py-2 text-[11px] text-muted"><span>You’re exploring a sample training week. Your own journey starts with an account.</span><Link href="/login" className="flex items-center gap-1 font-semibold">Make it yours<ArrowRight size={13}/></Link></div>}
    <section className="flex flex-wrap items-center justify-between gap-5 rounded-xl border border-line bg-white p-6">
      <div><p className="text-xs text-muted">Week {weekNumber}</p><h2 className="mt-2 text-xl font-semibold">{planName || 'Your next session'}</h2></div>
      <Link href="/workout" className="btn">Open workouts<ArrowRight size={16}/></Link>
    </section>
    <div className="my-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{[
      { label: 'Training sessions', value: `${metrics.sessions}`, suffix: 'this week', note: preview ? 'Consistency looks good on you' : 'Every session moves you forward', icon: Dumbbell, color: 'bg-emerald-50 text-emerald-700' },
      { label: 'Exercises completed', value: `${metrics.completed}`, suffix: 'this week', note: 'One rep closer to your goals', icon: Check, color: 'bg-canvas text-muted' },
      { label: 'Match days', value: `${scheduledMatches.length}`, suffix: 'per week', note: scheduledMatches.length ? scheduledMatches.map(d=>d.slice(0,3)).join(' · ') + ' · Make room for the game' : 'Set your schedule in Settings', icon: Volleyball, color: 'bg-canvas text-muted' },
      { label: 'Your focus', value: goal || 'Hybrid fitness', suffix: '', note: 'Strength + performance, in balance', icon: Target, color: 'bg-canvas text-muted' },
    ].map(({ label, value, suffix, icon: Icon, color })=><div key={label} className="card p-4"><div className="flex items-center justify-between"><p className="text-[11px] text-muted">{label}</p><span className={`rounded-lg p-2 ${color}`}><Icon size={16}/></span></div><div className="mt-2 flex flex-wrap items-baseline gap-2"><span className={`${label === 'Your focus' ? 'text-lg' : 'text-[27px]'} font-semibold tracking-tight`}>{value}</span><span className="text-[10px] text-muted">{suffix}</span></div></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.7fr_1fr]">
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-5"><h2 className="text-[15px] font-semibold">Your training week</h2><span className="rounded-md bg-canvas px-2 py-1 text-[9px] text-muted">Week {weekNumber.toString().padStart(2,'0')}</span></div><div className="grid grid-cols-7 gap-1.5 px-3 py-5 sm:gap-2 sm:px-5">{days.map((day, i)=>{const date = new Date(first); date.setDate(first.getDate()+i); const match = scheduledMatches.includes(day); const rest = !match && (i===3 || i===6); const Icon = match ? Volleyball : rest ? Footprints : Dumbbell; return <Link href={match || rest ? '/settings' : '/workout'} key={day} className={`flex min-w-0 flex-col items-center rounded-xl border px-1 py-3 transition hover:border-accent ${i===dayIndex ? 'border-accent bg-emerald-50' : 'border-transparent bg-canvas'}`}><span className={`text-[9px] ${i===dayIndex ? 'font-semibold text-accent' : 'text-muted'}`}>{day.slice(0,3)}</span><span className="mb-4 mt-2 text-base font-semibold">{date.getDate()}</span><span className={`rounded-full p-2 ${match ? 'bg-canvas text-muted' : rest ? 'text-muted' : i===dayIndex ? 'bg-accent text-white' : 'bg-white text-muted'}`}><Icon size={14}/></span><span className="mt-2 text-[8px] text-muted">{match ? 'Match' : rest ? 'Recover' : 'Strength'}</span>{i===dayIndex && <span className="mt-2 h-1 w-1 rounded-full bg-accent"/>}</Link>})}</div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-line px-5 py-3.5 text-[9px] text-muted"><div className="flex gap-3"><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-accent"/>Strength</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-canvas"/>Football</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-canvas"/>Recovery</span></div><Link href="/settings" className="flex items-center gap-1 font-medium text-ink">Adjust schedule<ChevronRight size={12}/></Link></div></section>
      <section className="card flex flex-col p-5"><div className="flex items-center justify-between"><span className="eyebrow">Up next</span><span className="rounded-full bg-canvas px-2 py-1 text-[9px] text-muted">Recommended session</span></div><div className="mb-3 mt-5 flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-accent"><Dumbbell size={23}/></div><div><h2 className="text-lg font-semibold tracking-tight">{planName || 'Full-body foundations'}</h2><p className="mt-1 text-[10px] text-muted">Calisthenics · Strength & control</p></div></div><div className="my-3 flex gap-5 text-[10px] text-muted"><span className="flex items-center gap-1.5"><Clock3 size={13}/>35–45 min</span><span className="flex items-center gap-1.5"><Zap size={13}/>4 exercises</span></div><Link href="/workout" className="mt-auto flex items-center justify-center gap-2 rounded-lg bg-accent py-3 text-xs font-semibold text-white transition hover:bg-emerald-800"><Play size={13} fill="currentColor"/>Start your workout<ArrowRight size={14} className="ml-auto mr-3"/></Link></section>
    </div>
    <div className="mt-5"><section className="card p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-[15px] font-semibold">Exercise library</h2></div><Link href="/exercises" className="flex items-center gap-1 text-[10px] font-semibold">Explore library<ArrowUpRight size={13}/></Link></div><div className="grid grid-cols-3 gap-3">{[{title:'Upper body',sub:'Push. Pull. Progress.',icon:Dumbbell,bg:'bg-canvas',text:'text-muted'},{title:'Lower body',sub:'Your engine for the pitch.',icon:Footprints,bg:'bg-canvas',text:'text-muted'},{title:'Core & control',sub:'It all starts here.',icon:Target,bg:'bg-canvas',text:'text-muted'}].map(({title,sub,icon:Icon,bg,text})=><Link href={`/exercises?category=${encodeURIComponent(title)}`} key={title} className="group"><div className={`relative flex h-24 items-center justify-center overflow-hidden rounded-xl ${bg}`}><Icon size={37} strokeWidth={1.2} className={`${text} transition group-hover:scale-110`}/><MoveUpRight size={12} className="absolute right-2 top-2 text-muted"/></div><h3 className="mt-3 text-[11px] font-semibold">{title}</h3><p className="mt-1 text-[9px] text-muted">{sub}</p></Link>)}</div></section></div>
  </AppShell>;
}
