import Link from 'next/link';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronRight, Clock3, Dumbbell, Flame, Footprints, MoveUpRight, Play, Target, TrendingUp, Volleyball, Zap } from 'lucide-react';
import { AppShell } from './app-shell';
import { days } from '@/lib/training';
type Props = { preview?: boolean; email?: string; completed?: number; sessions?: number; matchDays?: string[]; goal?: string; planName?: string; weekNumber?: number };
export function Dashboard({ preview = false, email, completed = 0, sessions = 0, matchDays = [], goal, planName, weekNumber = 1 }: Props) {
  const today = new Date();
  const todayIndex = (today.getDay() + 6) % 7;
  const dayIndex = preview ? 2 : todayIndex;
  const first = new Date(today); first.setDate(today.getDate() - todayIndex);
  const scheduledMatches = preview ? ['Saturday'] : matchDays;
  const metrics = preview ? { sessions: 3, completed: 18 } : { sessions, completed };
  return <AppShell preview={preview} email={email}>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow mb-2 text-accent">Your everyday, elevated</div><h1 className="text-[29px] font-semibold tracking-[-1px] sm:text-[34px]">Let’s build your better game<span className="text-accent">.</span></h1><p className="mt-2 text-[13px] text-muted">A stronger body. A sharper game. Your training starts here.</p></div><div className="flex items-center gap-2 rounded-lg border border-line bg-white px-3.5 py-2.5 text-[11px] text-muted"><CalendarDays size={14}/>{today.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</div></div>
    {preview && <div className="mb-5 flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[#e8dece] bg-[#f9f2e7] px-4 py-2 text-[11px] text-[#806b48]"><span>You’re exploring a sample training week. Your own journey starts with an account.</span><Link href="/login" className="flex items-center gap-1 font-semibold">Make it yours<ArrowRight size={13}/></Link></div>}
    <section className="relative overflow-hidden rounded-2xl bg-[#273e34] p-7 text-white sm:p-9">
      <div className="pitch-grid absolute inset-y-0 right-0 w-[52%] opacity-70"/>
      <svg className="absolute -right-8 -top-20 h-[420px] w-[470px] rotate-[-18deg] opacity-[0.17]" viewBox="0 0 470 420" fill="none" stroke="#d5e6c8" strokeWidth="1.5" aria-hidden="true"><rect x="72" y="35" width="300" height="390" rx="3"/><path d="M72 230h300"/><circle cx="222" cy="230" r="57"/><circle cx="222" cy="230" r="3" fill="#d5e6c8"/><path d="M145 35v75h155V35M178 35v28h87V35M145 425v-75h155v75"/><path d="M176 110a55 55 0 0 0 91 0M177 350a55 55 0 0 1 91 0"/></svg>
      <div className="absolute bottom-7 right-9 hidden flex-col items-end gap-3 md:flex"><div className="flex h-[95px] w-[95px] items-center justify-center rounded-full border border-[#99ad91]/30 bg-[#8a9c76]/10"><Volleyball size={60} strokeWidth={0.8} className="text-[#d9e3c9]"/></div><span className="text-[9px] uppercase tracking-[0.25em] text-[#b6c4b2]">Strength × Skill × Stamina</span></div>
      <div className="relative z-10 max-w-lg"><div className="mb-4 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em]"><span className="h-1.5 w-1.5 rounded-full bg-[#c2d7a5]"/><span className="text-[#d0dfbf]">The hybrid training method</span><span className="ml-2 rounded border border-white/20 px-2 py-0.5 text-[9px] font-normal tracking-normal">Week {weekNumber.toString().padStart(2,'0')}</span></div><h2 className="text-3xl font-medium leading-[1.16] tracking-[-1.2px] sm:text-[38px]">Strong on the bar.<br/><span className="text-[#cedcc0]">Unstoppable on the pitch.</span></h2><p className="mb-6 mt-4 max-w-sm text-xs leading-relaxed text-[#c1ccc3]">Purposeful calisthenics. Football-ready fitness.<br/>One balanced plan, built around your life.</p><Link href="/workout" className="inline-flex items-center gap-3 rounded-lg bg-[#eff3e7] px-4 py-3 text-xs font-semibold text-[#293d31]">Let’s get to work<ArrowUpRight size={16}/></Link></div>
    </section>
    <div className="my-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{[
      { label: 'Training sessions', value: `${metrics.sessions}`, suffix: 'this week', note: preview ? 'Consistency looks good on you' : 'Every session moves you forward', icon: Dumbbell, color: 'bg-[#f9ebe2] text-[#bd7b55]' },
      { label: 'Exercises completed', value: `${metrics.completed}`, suffix: 'this week', note: 'One rep closer to your goals', icon: Check, color: 'bg-[#edf0e5] text-[#7d8e5d]' },
      { label: 'Match days', value: `${scheduledMatches.length}`, suffix: 'per week', note: scheduledMatches.length ? scheduledMatches.map(d=>d.slice(0,3)).join(' · ') + ' · Make room for the game' : 'Set your schedule in Settings', icon: Volleyball, color: 'bg-[#e8eef3] text-[#758a9b]' },
      { label: 'Your focus', value: goal || 'Hybrid fitness', suffix: '', note: 'Strength + performance, in balance', icon: Target, color: 'bg-[#f3eede] text-[#a99860]' },
    ].map(({ label, value, suffix, note, icon: Icon, color })=><div key={label} className="card p-4"><div className="flex items-center justify-between"><p className="text-[11px] text-muted">{label}</p><span className={`rounded-lg p-2 ${color}`}><Icon size={16}/></span></div><div className="mt-2 flex flex-wrap items-baseline gap-2"><span className={`${label === 'Your focus' ? 'text-lg' : 'text-[27px]'} font-semibold tracking-tight`}>{value}</span><span className="text-[10px] text-muted">{suffix}</span></div><p className="mt-2 text-[9px] text-muted">{note}</p></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.7fr_1fr]">
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-5"><h2 className="text-[15px] font-semibold">Your training week</h2><span className="rounded-md bg-canvas px-2 py-1 text-[9px] text-muted">Week {weekNumber.toString().padStart(2,'0')}</span></div><div className="grid grid-cols-7 gap-1.5 px-3 py-5 sm:gap-2 sm:px-5">{days.map((day, i)=>{const date = new Date(first); date.setDate(first.getDate()+i); const match = scheduledMatches.includes(day); const rest = !match && (i===3 || i===6); const Icon = match ? Volleyball : rest ? Footprints : Dumbbell; return <Link href={match || rest ? '/settings' : '/workout'} key={day} className={`flex min-w-0 flex-col items-center rounded-xl border px-1 py-3 transition hover:border-accent ${i===dayIndex ? 'border-accent bg-[#fff5ee]' : 'border-transparent bg-[#f7f7f3]'}`}><span className={`text-[9px] ${i===dayIndex ? 'font-semibold text-accent' : 'text-muted'}`}>{day.slice(0,3)}</span><span className="mb-4 mt-2 text-base font-semibold">{date.getDate()}</span><span className={`rounded-full p-2 ${match ? 'bg-[#e7eddf] text-[#708557]' : rest ? 'text-[#a0a393]' : i===dayIndex ? 'bg-accent text-white' : 'bg-white text-[#828a75]'}`}><Icon size={14}/></span><span className="mt-2 text-[8px] text-muted">{match ? 'Match' : rest ? 'Recover' : 'Strength'}</span>{i===dayIndex && <span className="mt-2 h-1 w-1 rounded-full bg-accent"/>}</Link>})}</div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-line px-5 py-3.5 text-[9px] text-muted"><div className="flex gap-3"><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-accent"/>Strength</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-[#7a8c60]"/>Football</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-[#c6c9ba]"/>Recovery</span></div><Link href="/settings" className="flex items-center gap-1 font-medium text-ink">Adjust schedule<ChevronRight size={12}/></Link></div></section>
      <section className="card flex flex-col p-5"><div className="flex items-center justify-between"><span className="eyebrow">Up next</span><span className="rounded-full bg-[#f1f3e9] px-2 py-1 text-[9px] text-[#7a8860]">Recommended session</span></div><div className="mb-3 mt-5 flex items-center gap-3"><div className="rounded-xl bg-[#faeee6] p-3 text-accent"><Dumbbell size={23}/></div><div><h2 className="text-lg font-semibold tracking-tight">{planName || 'Full-body foundations'}</h2><p className="mt-1 text-[10px] text-muted">Calisthenics · Strength & control</p></div></div><div className="my-3 flex gap-5 text-[10px] text-muted"><span className="flex items-center gap-1.5"><Clock3 size={13}/>35–45 min</span><span className="flex items-center gap-1.5"><Zap size={13}/>4 exercises</span></div><p className="mb-5 text-[11px] leading-relaxed text-muted">Build the strength that carries over. Controlled reps, full range, and a little better than last time.</p><Link href="/workout" className="mt-auto flex items-center justify-center gap-2 rounded-lg bg-accent py-3 text-xs font-semibold text-white transition hover:bg-[#d65b2b]"><Play size={13} fill="currentColor"/>Start your workout<ArrowRight size={14} className="ml-auto mr-3"/></Link></section>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><section className="card p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-[15px] font-semibold">Build your movement toolkit</h2><p className="mt-1 text-[10px] text-muted">The fundamentals. Done well. Done often.</p></div><Link href="/exercises" className="flex items-center gap-1 text-[10px] font-semibold">Explore library<ArrowUpRight size={13}/></Link></div><div className="grid grid-cols-3 gap-3">{[{title:'Upper body',sub:'Push. Pull. Progress.',icon:Dumbbell,bg:'bg-[#ecefe7]',text:'text-[#849273]'},{title:'Lower body',sub:'Your engine for the pitch.',icon:Footprints,bg:'bg-[#f4eae0]',text:'text-[#b78d71]'},{title:'Core & control',sub:'It all starts here.',icon:Target,bg:'bg-[#e8eef0]',text:'text-[#7d969f]'}].map(({title,sub,icon:Icon,bg,text})=><Link href={`/exercises?category=${encodeURIComponent(title)}`} key={title} className="group"><div className={`relative flex h-24 items-center justify-center overflow-hidden rounded-xl ${bg}`}><span className="absolute h-20 w-20 rounded-full border border-white/50"/><span className="absolute h-32 w-32 rounded-full border border-white/50"/><Icon size={37} strokeWidth={1.2} className={`${text} transition group-hover:scale-110`}/><MoveUpRight size={12} className="absolute right-2 top-2 text-muted"/></div><h3 className="mt-3 text-[11px] font-semibold">{title}</h3><p className="mt-1 text-[9px] text-muted">{sub}</p></Link>)}</div></section><section className="flex flex-col rounded-2xl border border-[#e3e6d7] bg-[#eeefe4] p-5"><div className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[0.14em] text-[#798463]"><Flame size={14}/>The long game</div><h2 className="mt-5 text-xl font-medium leading-snug tracking-tight">Progress isn’t always louder.<br/>Sometimes it’s just showing up.</h2><p className="mb-5 mt-3 text-[11px] leading-relaxed text-[#858978]">Train with intention. Recover with purpose.<br/>The small things add up.</p><div className="mt-auto flex items-center gap-2 text-[10px] font-semibold text-[#6c7a53]"><TrendingUp size={15}/>Consistency over intensity.</div></section></div>
  </AppShell>;
}
