'use client';
import { useState } from 'react';
import { CustomExerciseForm } from './custom-exercise-form';
import { Search } from 'lucide-react';
import { ExerciseImage } from '@/components/exercise-image';
import { patterns, type Exercise } from '@/lib/training';
export function ExerciseLibrary({ exercises:initialExercises, initialCategory }: { exercises: Exercise[]; initialCategory?: string }) {
  const [exercises,setExercises] = useState(initialExercises);
  const [query,setQuery] = useState(''); const [pattern,setPattern] = useState('all'); const [category,setCategory] = useState(initialCategory || 'All movements');
  const filtered = exercises.filter(e=>e.name.toLowerCase().includes(query.toLowerCase()) && (pattern === 'all' || e.movement_pattern === pattern) && (category === 'All movements' || (category === 'Upper body' ? /push|pull/.test(e.movement_pattern) : category === 'Lower body' ? ['knee_dominant','hip_hinge','plyo'].includes(e.movement_pattern) : e.movement_pattern === 'core')));
  return <><CustomExerciseForm onCreated={exercise=>{setExercises(current=>[exercise,...current]);setQuery("");setPattern("all");setCategory("All movements");}}/><div className="mb-6 flex flex-wrap gap-3"><label className="relative min-w-48 flex-1"><span className="sr-only">Search exercises</span><Search className="absolute left-3 top-3.5 text-muted" size={16}/><input className="field pl-10" placeholder="Find your next movement…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select data-ui="select" aria-label="Movement category" className="field w-auto" value={category} onChange={e=>setCategory(e.target.value)}>{['All movements','Upper body','Lower body','Core & control'].map(c=><option key={c}>{c}</option>)}</select><select data-ui="select" aria-label="Movement pattern" className="field w-auto" value={pattern} onChange={e=>setPattern(e.target.value)}><option value="all">All patterns</option>{patterns.map(p=><option key={p} value={p}>{p.replaceAll('_',' ')}</option>)}</select></div><p className="mb-4 text-xs text-muted">{filtered.length} movements in your toolkit</p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(e=><article key={e.id} className="card overflow-hidden"><ExerciseImage name={e.name} url={e.gif_url} className="border-b border-line"/><div className="p-5"><p className="eyebrow">{e.movement_pattern.replaceAll('_',' ')}</p><h2 className="mt-2 text-lg font-semibold">{e.name}</h2><p className="mt-1 text-xs text-muted">{e.primary_muscle}</p><div className="mt-4 flex items-center justify-between gap-2 border-t border-line pt-3 text-[10px] text-muted"><span>{e.equipment.length ? e.equipment.join(', ') : 'Bodyweight'}</span><span>Level {e.difficulty}/5</span></div>{e.gif_url && /^https:\/\//.test(e.gif_url) && <a href={e.gif_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-xs font-semibold text-accent">Open image ↗</a>}<div className="mt-4"><CustomExerciseForm key={`${e.id}:${e.name}:${e.gif_url}:${e.difficulty}:${e.movement_pattern}:${e.primary_muscle}:${e.equipment.join(",")}`} exercise={e} copy={!e.user_id} onCreated={updated=>setExercises(current=>current.some(item=>item.id===updated.id)?current.map(item=>item.id===updated.id?updated:item):[updated,...current])}/></div></div></article>)}</div>{filtered.length === 0 && <div className="card p-10 text-center"><p className="font-medium">No movements found.</p><p className="mt-2 text-sm text-muted">Try a different search or movement category.</p><button className="btn mt-5" onClick={()=>{setQuery('');setPattern('all');setCategory('All movements');}}>Clear filters</button></div>}</>;
}
